spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto:
  h2:
    console:
      enabled: create

fileRepositoryFolder: C:\Users\linda\Downloads\UploaderDownloader